name: sushi_snap
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Packages
dependencies:
  flutter:
    sdk: flutter

  # Utility Specific

  # Icons
  cupertino_icons: ^1.0.6
  iconsax:

  google_fonts:

  # State Management
  get:
  provider:

  # Product Specific

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Local Assets
  assets:
    - lib/images/
    - lib/images/category/
    - lib/images/food/drinks/
    - lib/images/food/ramen/
    - lib/images/food/rice/
    - lib/images/food/salmon/
    - lib/images/food/shrimp/
    - lib/images/food/sushi/
    - assets/logo/
    - assets/icons/
    - assets/images/

  # Local Fonts
  fonts:
    - family: Shikamaru
      fonts:
        - asset: assets/fonts/shikamaru-shikamaru-400.otf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
